version: '2'
services:
  postgres:
    build: ./postgres/
    ports:
    - "5432:5432"
  caddy:
    image: abiosoft/caddy
    network_mode: host
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
    ports:
    - "80:80"
    - "443:443"
  identity:
    image: plumpack/identity-server:0.3.0-alpha.15
    volumes:
      - "./identity.yml:/etc/plumpack/identity-server/config.yml"
      - "./email.yml:/etc/plumpack/identity-server/email.yml"
      - "./plumpack.yml:/etc/plumpack/identity-server/plumpack.yml"
      - "./signing.yml:/etc/plumpack/identity-server/signing.yml"
      - "./key.pfx:/etc/plumpack/identity-server/key.pfx"
    ports:
    - "5000:5000"
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
